#pragma once

enum GameState {
  STATE_MAIN_MENU,
  STATE_STATUS,
  STATE_BATTLE_TEST,
  STATE_PILOT_RECORD,
  STATE_OPTIONS,
  STATE_CREDITS,
  STATE_WIN_SCREEN,
  STATE_PLAYER_NAME,
  STATE_PLAYER_FACTION
};